#ifndef GADDLE_BACKEND_GLOBAL_H
#define GADDLE_BACKEND_GLOBAL_H

#include "minimize.h"

#if defined(GADDLE_BACKEND_LIBRARY)
#  define GADDLE_BACKENDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GADDLE_BACKENDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GADDLE_BACKEND_GLOBAL_H
